### ISSUE TITLE
Greater than greater than

### ISSUE THREAD

**Issue by anthonyesau** [anthonyesau/sass-tools#3]
For the responder tool, prevent errors of requesting a media query that is greater than a media query that is greater than some measurement such as this

``` scss
$media-queries: (
  sm: ("<", 640px),
  md: (641px, 1280px),
  lg: (">", 1281px)
);

@include media('>=lg') {
  .foo {
    display
  }
};
```

from which the compiler will spit out an error such as this

```
Error: Invalid null operation: """ plus null".
        on line 160 of /scss/vendors/sass-tools/_responder.scss, in `media'
        from line 7 of /scss/partials/_style.scss
```

Perhaps there should be a debug error thrown. Or it should automatically be handled as a query containing only one greater than; the redundancy is negated (but could still supply a suggestion as a warning not to double up on the greater thans). Add this suggestion to the docs as well.

This may also occur for less than comparisons.
