### ISSUE TITLE
Media query range by name

### ISSUE THREAD

**Issue by anthonyesau** [anthonyesau/sass-tools#5]
This should be possible:

```
@include media('sm', 'lg') {
  /*content*/
}
```

**Comment by anthonyesau** [comment]
Starting place is `_responder.scss` line 115.

The first bit of code to get you going should be to replace that line with
```scss
      $one: nth($query, 1);
      $two: nth($query, 2);
      @if type-of($one) == "string" and type-of($two) == "string" {
        $one: find-query($one);
        $two: find-query($two);
      }
      $media-width: media-width($one, $two);
```

I had apparently begun to address this issue but didn't finish.
